project_id = "yfivkhczzywgttbgwtgr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
pop3_port = 54326
smtp_port = 54327

[functions.trigger-slack]
verify_jwt = false

[functions.slack-notification]
verify_jwt = false

[functions.google-sheets-update]
verify_jwt = false

[functions.process-lead]
verify_jwt = false

[functions.docusign-connect-webhook]
verify_jwt = false

[functions.aloware-recording-webhook]
verify_jwt = false

[functions.get-lead-call-recordings]
verify_jwt = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[edge_runtime]
enabled = true
